In [6]:
from gym_ur.game_of_ur import GoUrEnv
import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict

plt.style.use('ggplot')

SyntaxError: invalid syntax (<ipython-input-6-c93a96545cf9>, line 1)

In [2]:
env = GoUrEnv()

NameError: name 'GoUrEnv' is not defined

In [3]:
env.get_possible_actions(1, 3)


[{'curr_pos': 0,
  'double_move': False,
  'next_pos': ('c', 2),
  'piece_id': (1, 0),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('c', 2),
  'piece_id': (1, 1),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('c', 2),
  'piece_id': (1, 2),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('c', 2),
  'piece_id': (1, 3),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('c', 2),
  'piece_id': (1, 4),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('c', 2),
  'piece_id': (1, 5),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('c', 2),
  'piece_id': (1, 6),
  'replace_opp': False}]

In [4]:
env.postions[0][1] = ('a', 1)

In [5]:
env.postions[0]

array([0, ('a', 1), 0, 0, 0, 0, 0], dtype=object)

In [6]:
env.get_possible_actions(0, 4)

[{'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 5),
  'piece_id': (0, 0),
  'replace_opp': False},
 {'curr_pos': ('a', 1),
  'double_move': True,
  'next_pos': ('b', 4),
  'piece_id': (0, 1),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 5),
  'piece_id': (0, 2),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 5),
  'piece_id': (0, 3),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 5),
  'piece_id': (0, 4),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 5),
  'piece_id': (0, 5),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 5),
  'piece_id': (0, 6),
  'replace_opp': False}]

In [7]:
env.postions[1][1] = ('b', 4)

In [8]:
env.postions[1]

array([0, ('b', 4), 0, 0, 0, 0, 0], dtype=object)

In [9]:
env.get_possible_actions(0, 4)

[{'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 5),
  'piece_id': (0, 0),
  'replace_opp': False},
 {'curr_pos': ('a', 1),
  'double_move': False,
  'next_pos': ('b', 5),
  'piece_id': (0, 1),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 5),
  'piece_id': (0, 2),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 5),
  'piece_id': (0, 3),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 5),
  'piece_id': (0, 4),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 5),
  'piece_id': (0, 5),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 5),
  'piece_id': (0, 6),
  'replace_opp': False}]

In [10]:
env.postions[1][1] = ('b', 3)

In [11]:
env.postions[1]

array([0, ('b', 3), 0, 0, 0, 0, 0], dtype=object)

In [12]:
env.get_possible_actions(0, 3)

[{'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 2),
  'piece_id': (0, 0),
  'replace_opp': False},
 {'curr_pos': ('a', 1),
  'double_move': False,
  'next_pos': ('b', 3),
  'piece_id': (0, 1),
  'replace_opp': True},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 2),
  'piece_id': (0, 2),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 2),
  'piece_id': (0, 3),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 2),
  'piece_id': (0, 4),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 2),
  'piece_id': (0, 5),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': False,
  'next_pos': ('a', 2),
  'piece_id': (0, 6),
  'replace_opp': False}]

In [13]:
env.postions[0][1] = ('b', 8)

In [22]:
env.get_possible_actions(0, 4)

[{'curr_pos': 0,
  'double_move': True,
  'next_pos': ('a', 1),
  'piece_id': (0, 0),
  'replace_opp': False},
 {'curr_pos': ('b', 8),
  'double_move': False,
  'next_pos': ('b', 8),
  'piece_id': (0, 1),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': True,
  'next_pos': ('a', 1),
  'piece_id': (0, 2),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': True,
  'next_pos': ('a', 1),
  'piece_id': (0, 3),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': True,
  'next_pos': ('a', 1),
  'piece_id': (0, 4),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': True,
  'next_pos': ('a', 1),
  'piece_id': (0, 5),
  'replace_opp': False},
 {'curr_pos': 0,
  'double_move': True,
  'next_pos': ('a', 1),
  'piece_id': (0, 6),
  'replace_opp': False}]